name: Docker Image CI to ACR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  REGISTRY: $"https://${{ secrets.AZ_REGISTER_URL }}/"
  REGISTRY_OWNER: ${{ secrets.AZ_REGISTER_USERNAME }} 
  REGISTRY_NAME: ${{ secrets.AZ_REGISTER_USERNAME }} 
  IMAGE_NAME: grandnode2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}
    - uses: actions/checkout@v3
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
      # Container registry username
        username: ${{ secrets.AZ_REGISTER_USERNAME }} 
      # Container registry password
        password: ${{ secrets.AZ_REGISTER_PASSWORD }} 
      # Container registry server url
        login-server: ${{ secrets.AZ_REGISTER_URL }} 
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CONTAINER_USER_NAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

    - name: Push container to Azure Container Registry
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_OWNER }}.azurecr.io/${{env.IMAGE_NAME}}:${{ env.RELEASE_VERSION }}
